### ISSUE TITLE
Watch system clipboard

### ISSUE THREAD

**Issue by kankaristo** [aki77/atom-clipboard-plus#1]
I know this is in the to-do list in README.md, but I'm creating an issue just so I can track when this is implemented. :grin:

Thanks for a great package!

**Comment by kankaristo** [comment]
For basic support, I guess you could just insert the value from `atom.clipboard.read()` into the clipboard list every time it's toggled (unless the same value is on top already).

I doubt that you could track copies made outside of Atom in any other way.

**Comment by aki77** [comment]
Thank you for a request.

**Comment by aki77** [comment]
Please try the latest version.

**Comment by kankaristo** [comment]
@aki77, I'm getting an error with the new version (0.2.0):

``` coffee
TypeError: undefined is not a function
  at ClipboardListView.module.exports.ClipboardListView.toggle (/home/sami/.atom/packages/clipboard-plus/lib/clipboard-list-view.coffee:46:33)
  at Object.module.exports.toggle (/home/sami/.atom/packages/clipboard-plus/lib/main.coffee:49:24)
  at atom-text-editor.subscription.atom.commands.add.clipboard-plus:toggle (/home/sami/.atom/packages/clipboard-plus/lib/main.coffee:32:36)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)
```

**Comment by aki77** [comment]
What is the version of atom?

**Comment by kankaristo** [comment]
Atom 0.207.0. My system is Ubuntu 14.04.2.

**Comment by aki77** [comment]
Bug is not reproducible.
Please try devTools.

```
atom.packages.getActivePackage('clipboard-plus').mainModule.clipboardItems.syncSystemClipboard
```

[![Gyazo](http://i.gyazo.com/db0ffa1d4127ae8c60e9708aeba37c2b.png)](http://gyazo.com/db0ffa1d4127ae8c60e9708aeba37c2b)

**Comment by kankaristo** [comment]
@aki77, I don't know what was going on, the bug disappeared after uninstalling and reinstalling the package.

Thanks for adding support for the system clipboard! :+1:

**Comment by aki77** [comment]
:smile:
