### ISSUE TITLE
Failed to activate the clipboard-plus package

### ISSUE THREAD

**Issue by shishi** [aki77/atom-clipboard-plus#9]
**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [clipboard-plus](https://github.com/aki77/atom-clipboard-plus) package, v0.5.1
### Stack Trace

Failed to activate the clipboard-plus package

```
At Cannot find module 'property-accessors'

Error: Cannot find module 'property-accessors'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/local/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/local/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/shishi/spideroak_sync/conf/atom/packages/clipboard-plus/node_modules/@aki77/atom-select-action/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/grim/node_modules/emissary/lib/behavior.js:9:23)
    at Object.<anonymous> (/Users/shishi/spideroak_sync/conf/atom/packages/clipboard-plus/node_modules/@aki77/atom-select-action/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/grim/node_modules/emissary/lib/behavior.js:120:4)
    at Module._compile (/usr/local/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/local/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/local/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/shishi/spideroak_sync/conf/atom/packages/clipboard-plus/node_modules/@aki77/atom-select-action/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/grim/node_modules/emissary/lib/helpers.js:5:14)
    at Object.<anonymous> (/Users/shishi/spideroak_sync/conf/atom/packages/clipboard-plus/node_modules/@aki77/atom-select-action/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/grim/node_modules/emissary/lib/helpers.js:55:4)
    at Module._compile (/usr/local/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/local/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/local/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/shishi/spideroak_sync/conf/atom/packages/clipboard-plus/node_modules/@aki77/atom-select-action/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/grim/node_modules/emissary/lib/emissary.js:4:13)
    at Object.<anonymous> (/Users/shishi/spideroak_sync/conf/atom/packages/clipboard-plus/node_modules/@aki77/atom-select-action/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/grim/node_modules/emissary/lib/emissary.js:14:4)
    at Module._compile (/usr/local/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/local/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/local/Caskroom/atom/1.3.2/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/shishi/spideroak_sync/conf/atom/packages/clipboard-plus/node_modules/@aki77/atom-select-action/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/grim/lib/grim.js:4:13)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-rubocop"
    ]
  },
  "clipboard-plus": {}
}
```
### Installed Packages

``` coffee
# User
atomatigit, v1.5.5
auto-indent, v0.5.0
clipboard-plus, v0.5.1
disable-keybindings, v0.6.0
emacs-plus, v0.9.11
file-icons, v1.6.14
file-types, v0.5.1
git-log, v0.4.1
jshint, v1.8.3
language-diff, v0.4.0
language-rspec, v0.3.0
linter, v1.11.3
linter-coffeescript, v1.0.0
linter-erb, v1.0.2
linter-haml, v1.1.0
linter-ruby, v1.2.1
linter-sass-lint, v1.0.4
linter-scss-lint, v2.5.1
ruby-block, v0.3.5
tualo-git-context, v0.6.17

# Dev
No dev packages
```

**Comment by aki77** [comment]
I can't reproduce the error.
Please try re-install.

```
apm uninstall clipboard-plus
apm install clipboard-plus
```

**Comment by shishi** [comment]
Fixed! Thank you.

**Comment by aki77** [comment]
:smiley:
